basePath: /api/v1
definitions:
  router.ErrorResponse:
    properties:
      error: {}
    type: object
  router.MessageResponse:
    properties:
      message:
        type: string
    type: object
  types.Fact:
    properties:
      approved:
        type: boolean
      category:
        type: string
      id:
        type: string
      source:
        type: string
      text:
        type: string
    type: object
host: https://animalfacts.app
info:
  contact:
    email: support@animalfacts.app
    name: Animal Facts API
    url: https://animalfacts.app
  description: Awesome facts about animals.
  license:
    name: MIT
    url: https://github.com/cafo13/animal-facts/blob/main/LICENSE
  title: Animal Facts API
  version: "1.0"
paths:
  /fact:
    get:
      description: Getting a random animal fact
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Fact'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.ErrorResponse'
      summary: Get random animal fact
      tags:
      - facts
    post:
      consumes:
      - application/json
      description: Updating an animal fact
      parameters:
      - description: an updated fact
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.Fact'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Fact'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/router.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.ErrorResponse'
      summary: Update an existing animal fact
      tags:
      - facts
  /fact/:id:
    delete:
      description: Deleting an animal fact
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.ErrorResponse'
      summary: Delete an animal fact
      tags:
      - facts
    get:
      description: Getting an animal fact by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Fact'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/router.ErrorResponse'
      summary: Get animal fact by id
      tags:
      - facts
  /healthy:
    get:
      description: Checking the health of the API
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get health status
      tags:
      - general
swagger: "2.0"
