FROM golang:1.21

WORKDIR /animal-facts-public

COPY . .
RUN go mod download && go mod verify
RUN CGO_ENABLED=0 GOOS=linux go build -o /animal-facts-public/api -ldflags "-s -w" cmd/public-api/main.go

CMD ["/animal-facts-public/api"]
