version: '3.1'

services:

  animalfacts:
    image: animalfacts:testing
    container_name: animalfacts
    environment:
      MONGODB_CONNSTRING: "mongodb://animalfacts:animalfacts@mongodb:27017"
      MONGODB_DBNAME: "animalfacts"
      API_PORT: 80
      ENV GIN_MODE: "release"
    ports:
      - '8080:80'
    networks:
      - animalfacts

  mongo:
    image: mongo:6.0.3
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: animalfacts
      MONGO_INITDB_ROOT_PASSWORD: animalfacts
    ports:
      - '27017:27017'
    volumes:
      - /etc/animalfacts/db:/data/db
    networks:
      - animalfacts

networks:
  animalfacts:
    external: true
