basePath: /api/v1
definitions:
  api.CountResult:
    properties:
      count:
        type: integer
    type: object
  api.ErrorResult:
    properties:
      error:
        type: string
    type: object
  handler.Fact:
    properties:
      fact:
        type: string
      id:
        type: string
      source:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: https://animal-facts.cafo.dev
info:
  contact: {}
  description: This API provides facts about animals.
  license:
    name: MIT
    url: https://github.com/cafo13/animal-facts/blob/main/LICENSE
  title: Animal Facts Public API
  version: 0.0.4
paths:
  /facts:
    get:
      description: gets random fact from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Fact'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResult'
      summary: gets random fact
  /facts/:id:
    get:
      description: gets fact by ID from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Fact'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResult'
      summary: gets fact
  /facts/count:
    get:
      description: gets fact count from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CountResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResult'
      summary: gets fact count
swagger: "2.0"
