// Package facts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package facts

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Fact defines model for Fact.
type Fact struct {
	Source string             `json:"source"`
	Text   string             `json:"text"`
	Uuid   openapi_types.UUID `json:"uuid"`
}

// UpdateFact defines model for UpdateFact.
type UpdateFact struct {
	Source string `json:"source"`
	Text   string `json:"text"`
}
