name: animal_facts

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/animal-facts.yml
      - cmd/
      - internal-api/
      - public-api/
      - pkg/
      - Dockerfile_internal_api
      - Dockerfile_public_api
      - Makefile
      - go.mod
      - go.sum

jobs:
  semver:
    name: Generate semantic version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: semver
        name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}"
          change_path: "cmd internal-api public-api pkg"
          bump_each_commit: true
          search_commit_body: true
          user_format_type: "json"

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: golang:1.21
    env:
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      MONGODB_DATABASE_NAME: ${{secrets.MONGODB_DATABASE_NAME}}
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install dependencies
        run: go mod download
      - name: run tests
        run: make test

  build-public-api:
    name: Build public api
    needs: [
      semver,
      tests
    ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: replace version
        run: sed -i "s/VERSION_PLACEHOLDER/${{ needs.semver.outputs.version }}/g" public-api/server/server.go
      - name: update swagger
        run: make public-api-generate-swagger
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile_public_api
          push: true
          tags: |
            ghcr.io/cafo13/animal-facts/public-api:${{ needs.semver.outputs.version }}
            ghcr.io/cafo13/animal-facts/public-api:latest


  build-internal-api:
    name: Build internal api
    needs: [
      semver,
      tests
    ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: replace version
        run: sed -i "s/VERSION_PLACEHOLDER/${{ needs.semver.outputs.version }}/g" internal-api/server/server.go
      - name: update swagger
        run: make internal-api-generate-swagger
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile_internal_api
          push: true
          tags: |
            ghcr.io/cafo13/animal-facts/internal-api:${{ needs.semver.outputs.version }}
            ghcr.io/cafo13/animal-facts/internal-api:latest

  tag_and_release:
    name: Tag repo and create release
    needs: [
      semver,
      build-public-api,
      build-internal-api
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Tag
        id: create_tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.semver.outputs.version }}
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.semver.outputs.version }}
          body: ${{ github.event.head_commit.message }}
