name: animal_facts

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/animal-facts.yml
      - cmd/**
      - internal-api/**
      - public-api/**
      - pkg/**
      - Dockerfile_internal_api
      - Dockerfile_public_api
      - Makefile
      - go.mod
      - go.sum

jobs:
  semver:
    name: Set semantic version from repo
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.VERSION }}
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - id: semver
        name: set version output
        run: echo "VERSION=$(cat version.txt)" >> "$GITHUB_OUTPUT"

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: golang:1.21
    env:
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      MONGODB_DATABASE_NAME: ${{secrets.MONGODB_DATABASE_NAME}}
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install dependencies
        run: go mod download
      - name: run tests
        run: make test

  build-public-api:
    name: Build public api
    needs: [
      semver,
      tests
    ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Tag Docker image and push to GitHub Artifact Registry
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile_public_api
          push: true
          tags: |
            ghcr.io/cafo13/animal-facts/public-api:${{ needs.semver.outputs.VERSION }}
            ghcr.io/cafo13/animal-facts/public-api:latest


  build-internal-api:
    name: Build internal api
    needs: [
      semver,
      tests
    ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Tag Docker image and push to GitHub Artifact Registry
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile_internal_api
          push: true
          tags: |
            ghcr.io/cafo13/animal-facts/internal-api:${{ needs.semver.outputs.VERSION }}
            ghcr.io/cafo13/animal-facts/internal-api:latest

  tag_and_release:
    name: Tag repo and create release
    needs: [
      semver,
      build-public-api,
      build-internal-api
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Tag
        id: create_tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.semver.outputs.VERSION }}
          force_push_tag: true
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.semver.outputs.VERSION }}
          body: ${{ github.event.head_commit.message }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
