name: backend

on:
  push:
    branches: ["main"]
    paths:
      - backend/**
      - .github/workflows/backend.yml
  pull_request:
    branches: ["main"]
    paths:
      - backend/**
      - .github/workflows/backend.yml

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: golang:1.19.4
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: install dependencies
        run: go mod download
        working-directory: ./backend
      - name: run tests
        run: go test ./...
        working-directory: ./backend
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE_NAME: ${{ github.repository }}/backend
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.REGISTRY_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.REGISTRY_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: |
             europe-west4-docker.pkg.dev/animal-facts-project/animal-facts/backend:${{ steps.get-tag.outputs.short_ref }}
             europe-west4-docker.pkg.dev/animal-facts-project/animal-facts/backend:latest
