name: cli

on:
  push:
    branches: ["main"]
    paths:
      - cli/**
      - .github/workflows/cli.yml
  pull_request:
    branches: ["main"]
    paths:
      - cli/**
      - .github/workflows/cli.yml
      - go.work
      - go.work.sum

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: golang:1.19.4
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: install dependencies
        run: go mod download
        working-directory: ./cli
      - name: run tests
        run: go test ./...
        working-directory: ./cli
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ github.repository }}/cli
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: build cli
        run: echo "[TODO] cli tool will be built here..."
