name: Build and deploy frontend to firebase hosting

on:
  push:
    branches: ["main"]
    paths:
      - frontend/**
      - .github/workflows/frontend.yml

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn && yarn build
        working-directory: ./frontend
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANIMAL_FACTS_PROJECT }}'
          channelId: live
          projectId: animal-facts-project
          entryPoint: ./frontend
