name: frontend

on:
  push:
    branches: ["main"]
    paths:
      - frontend/**
      - .github/workflows/frontend.yml
  pull_request:
    branches: ["main"]
    paths:
      - frontend/**
      - .github/workflows/frontend.yml

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
    env:
      CHROME_BIN: '/usr/bin/chromium'
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name:
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          apt-get update
          apt-get install google-chrome-stable
        working-directory: ./frontend
      - name: run tests
        run: yarn test:ci
        working-directory: ./frontend
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ github.repository }}/frontend
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
