name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install dependencies
        run: yarn install
        working-directory: ./frontend
      - name: run tests
        run: yarn test:ci
        working-directory: ./frontend
  test-api:
    name: Test API
    runs-on: ubuntu-latest
    container:
      image: golang:1.19.4
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: install dependencies
        run: go mod download && go mod verify
        working-directory: ./api
      - name: run tests
        run: go test ./...
        working-directory: ./api
