name: Test

on:
  push:
    branches: ["main"]
  pull_requests:
    branches: ["main"]

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: cd into to working directory
        run: cd ./frontend
      - name: install dependencies
        run: yarn install
      - name: run tests
        run: yarn test
  test-api:
    name: Test API
    runs-on: ubuntu-latest
    container:
      image: golang:1.19.4
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: cd into to working directory
        run: cd ./api
      - name: install dependencies
        run: go mod download && go mod verify
      - name: run tests
        run: go test ./...
